module.exports = [
  'AC Repair Technician',
  'Architect',
  'Auto Mechanic',
  'Barber',
  'Beautician',
  'Builder',
  'Carpenter',
  'Caterer',
  'Civil Engineer',
  'Cleaner',
  'Consultant',
  'Content Writer',
  'Data Analyst',
  'Designer',
  'Developer',
  'DevOps Engineer',
  'Digital Marketer',
  'Doctor',
  'Driver',
  'Electrician',
  'Event Planner',
  'Graphic Designer',
  'Home Tutor',
  'House Cleaner',
  'Interior Designer',
  'Lawyer',
  'Mason',
  'Mobile Repair Technician',
  'Painter',
  'Photographer',
  'Plumber',
  'Product Manager',
  'SEO Specialist',
  'Security Guard',
  'Software Engineer',
  'Teacher',
  'UI/UX Designer',
  'Veterinarian',
  'Videographer',
  'Virtual Assistant',
  'Web Designer',
  'Web Developer'
];
