module.exports = [
  'AC Repair Technician',
  'Architect',
  'Auto Mechanic',
  'Barber',
  'Beautician',
  'Builder',
  'Carpenter',
  'Caterer',
  'Civil Engineer',
  'Cleaner',
  'Consultant',
  'Content Writer',
  'Data Analyst',
  'Designer',
  'Developer',
  'DevOps Engineer',
  'Digital Marketer',
  'Doctor',
  'Driver',
  'Electrician',
  'Event Planner',
  'Graphic Designer',
  'Dhol Player',
  'Home Tutor',
  'House Cleaner',
  'Interior Designer',
  'Lawyer',
  'Mason',
  'Mehendi Artist',
  'Mobile Repair Technician',
  'Painter',
  'Photographer',
  'Plumber',
  'Product Manager',
  'SEO Specialist',
  'Security Guard',
  'Software Engineer',
  'Teacher',
  'UI/UX Designer',
  'Veterinarian',
  'Videographer',
  'Virtual Assistant',
  'Wedding Decorator',
  'Web Designer',
  'Web Developer',
  'Ghodi Service'
];
